package climateheroapp;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Prathibha Kirthi
 */
public class ClimateHeroRegisterGUI extends javax.swing.JFrame {

    private ArrayList<UserForm> players;

    /**
     * Creates new form ClimateGUI
     */
    public ClimateHeroRegisterGUI() {
        initComponents();
        players = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        dobLbl = new javax.swing.JLabel();
        phoneNoLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        tagline1Lbl = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        dobTf = new javax.swing.JTextField();
        phoneNoTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        searchBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        titleLbl.setBackground(new java.awt.Color(204, 255, 255));
        titleLbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 153, 153));
        titleLbl.setText("WELCOME TO CLIMATE HERO ");

        nameLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(0, 153, 153));
        nameLbl.setText("NAME:");

        emailLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(0, 153, 153));
        emailLbl.setText("EMAIL:");

        dobLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        dobLbl.setForeground(new java.awt.Color(0, 153, 153));
        dobLbl.setText("DATE OF BIRTH:");

        phoneNoLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        phoneNoLbl.setForeground(new java.awt.Color(0, 153, 153));
        phoneNoLbl.setText("PHONE NUMBER:");

        passwordLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(0, 153, 153));
        passwordLbl.setText("PASSWORD:");

        registerBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 153, 153));
        registerBtn.setText("REGISTER");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        tagline1Lbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        tagline1Lbl.setForeground(new java.awt.Color(0, 153, 153));
        tagline1Lbl.setText("Please fill out your details to register !");

        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        phoneNoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTfActionPerformed(evt);
            }
        });

        emailTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTfActionPerformed(evt);
            }
        });

        passwordTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTfActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(0, 153, 153));
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        printBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        printBtn.setForeground(new java.awt.Color(0, 153, 153));
        printBtn.setText("PRINT ");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 204, 255));
        backBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 153, 153));
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tagline1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(nameLbl)
                                            .addGap(93, 93, 93)
                                            .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(phoneNoLbl)
                                                .addComponent(emailLbl)
                                                .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dobTf, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                                .addComponent(phoneNoTf)
                                                .addComponent(emailTf)
                                                .addComponent(passwordTf)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(129, 129, 129)
                                    .addComponent(titleLbl))))
                        .addGap(0, 141, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(registerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(nameLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tagline1Lbl)
                        .addGap(18, 18, 18)
                        .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLbl)
                    .addComponent(dobTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNoLbl)
                    .addComponent(phoneNoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(searchBtn)
                    .addComponent(printBtn)
                    .addComponent(backBtn)
                    .addComponent(saveBtn))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void phoneNoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTfActionPerformed

    private void emailTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTfActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        UserForm f = new UserForm();
        f.setName(nameTf.getText());
        f.setDateOfBirth(dobTf.getText());
        f.setPhoneNo(Integer.parseInt(phoneNoTf.getText()));
        f.setEmail(emailTf.getText());
        f.setPassword(passwordTf.getText());
        players.add(f);

    }//GEN-LAST:event_registerBtnActionPerformed

    private void passwordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTfActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_passwordTfActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if (players.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no players to search for");
        } else {
            String searchTerm = JOptionPane.showInputDialog(null, "Please enter a name of the player to search for");
            boolean playerFound = false;

            for (UserForm u : players) {
                if (u.getName().equalsIgnoreCase(searchTerm)) {
                    JOptionPane.showMessageDialog(null, u.getDetails());
                    playerFound = true;
                    break; // No need to continue searching once a match is found
                }
            }

            if (!playerFound) {
                JOptionPane.showMessageDialog(null, "Sorry, no player with the given name found");
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // TODO add your handling code here:
        for (UserForm u : players) {
            JOptionPane.showMessageDialog(null, u.getDetails());
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
//        ClimateHeroMainGUI myGUI = new ClimateHeroMainGUI();
//        myGUI.setVisible(true);
//        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (players != null) {
            File f;
            FileOutputStream fStream;
            ObjectOutputStream oStream;
            try {
                f = new File("Output.data");
                fStream = new FileOutputStream(f);
                oStream = new ObjectOutputStream(fStream);

                oStream.writeObject(players);
                oStream.close();
            } catch (IOException u) {
                System.out.println("Error: players list is null");
            }
            ClimateHeroMenuGUI myGUI = new ClimateHeroMenuGUI();
            myGUI.setVisible(true);
            dispose();
            }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClimateHeroRegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClimateHeroRegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClimateHeroRegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClimateHeroRegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClimateHeroRegisterGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTf;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JLabel phoneNoLbl;
    private javax.swing.JTextField phoneNoTf;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel tagline1Lbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

}
