/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateheroapp;

import javax.swing.JOptionPane;

/**
 *
 * @author Prathibha Kirthi
 */
public class FoodGUI extends javax.swing.JFrame {
    
    private int score;
    private double carbon;

    /**
     * Creates new form FoodGUI
     */
    public FoodGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        tagLineLbl = new javax.swing.JLabel();
        food1Box = new javax.swing.JCheckBox();
        food2Box = new javax.swing.JCheckBox();
        food3Box = new javax.swing.JCheckBox();
        food4Box = new javax.swing.JCheckBox();
        food5Box = new javax.swing.JCheckBox();
        food6Box = new javax.swing.JCheckBox();
        scoreBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        checkBtn = new javax.swing.JButton();
        factBtn = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        questionLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("\"Empower Your Plate, Empower the Planet: Savoring Sustainable Choices for a Greener Tomorrow!\"");

        tagLineLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        tagLineLbl.setForeground(new java.awt.Color(255, 0, 0));
        tagLineLbl.setText("Please check off the list of things you did today towards a greener future !");

        food1Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        food1Box.setText("Reduce meat consumption ");
        food1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food1BoxActionPerformed(evt);
            }
        });

        food2Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        food2Box.setText("Avoided single-use plastic !");
        food2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food2BoxActionPerformed(evt);
            }
        });

        food3Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        food3Box.setText("Planed meals to minimise waste ");
        food3Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food3BoxActionPerformed(evt);
            }
        });

        food4Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        food4Box.setText("Ate locally produced food ");
        food4Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food4BoxActionPerformed(evt);
            }
        });

        food5Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        food5Box.setText("Used re-usable cutlery, water bottle and coffee cup ");
        food5Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food5BoxActionPerformed(evt);
            }
        });

        food6Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        food6Box.setText("Composted kitchen scraps ");
        food6Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food6BoxActionPerformed(evt);
            }
        });

        scoreBtn.setBackground(new java.awt.Color(51, 255, 255));
        scoreBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        scoreBtn.setText("Score");
        scoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 204, 255));
        backBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        backBtn.setText("Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        checkBtn.setBackground(new java.awt.Color(51, 255, 255));
        checkBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        checkBtn.setText("Check me!");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        factBtn.setBackground(new java.awt.Color(0, 255, 255));
        factBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        factBtn.setText("Fact of the day");
        factBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factBtnActionPerformed(evt);
            }
        });

        questionLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        questionLbl.setText("How happy were you with your contribution today ?");
        questionLbl.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)), null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(food1Box, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(questionLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(scoreBtn)
                                .addGap(44, 44, 44)
                                .addComponent(checkBtn)
                                .addGap(44, 44, 44)
                                .addComponent(factBtn)
                                .addGap(33, 33, 33)
                                .addComponent(backBtn))
                            .addComponent(food4Box, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(food3Box, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tagLineLbl)
                            .addComponent(titleLbl)
                            .addComponent(food6Box, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(food5Box, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(food2Box, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addComponent(tagLineLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(food1Box, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(food2Box)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(food3Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(food4Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(food5Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(food6Box, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreBtn)
                    .addComponent(checkBtn)
                    .addComponent(factBtn)
                    .addComponent(backBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void food1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food1BoxActionPerformed
        // TODO add your handling code here:
         if (food1Box.isSelected()) {
                    score  = score + 5;
                    carbon =  carbon + 12.9;
                }
    }//GEN-LAST:event_food1BoxActionPerformed

    private void food2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food2BoxActionPerformed
        // TODO add your handling code here:
      if (food2Box.isSelected()) {
                    score  = score + 5;
                    carbon =  carbon + 13.9;
                }
    }//GEN-LAST:event_food2BoxActionPerformed

    private void scoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBtnActionPerformed
        // TODO add your handling code here:
        
            JOptionPane.showMessageDialog(null,"Your Score is:"+score);
        
        
    }//GEN-LAST:event_scoreBtnActionPerformed

    private void food3BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food3BoxActionPerformed
        // TODO add your handling code here:
        if (food3Box.isSelected()) {
                    score  = score + 5;
                    carbon =  carbon + 12.12;
                }
    }//GEN-LAST:event_food3BoxActionPerformed

    private void food4BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food4BoxActionPerformed
        // TODO add your handling code here:
        if (food4Box.isSelected()) {
                    score  = score + 5;
                    carbon = carbon + 13.3;
                }
    }//GEN-LAST:event_food4BoxActionPerformed

    private void food5BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food5BoxActionPerformed
        // TODO add your handling code here:
        if (food5Box.isSelected()) {
                    score  = score + 5;
                    carbon= carbon + 13.9;
                }
    }//GEN-LAST:event_food5BoxActionPerformed

    private void food6BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food6BoxActionPerformed
        // TODO add your handling code here:
        if (food6Box.isSelected()) {
                    score  = score + 5;
                    carbon =  carbon +14.9;
                }
    }//GEN-LAST:event_food6BoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ClimateHeroFoodWasteGUI myGUI = new ClimateHeroFoodWasteGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Carbon footprint that you have NOT emitted because of doing your activities is:"+carbon+" CO2e");
    }//GEN-LAST:event_checkBtnActionPerformed

    private void factBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Roughly one-third of the food produced for human consumption globally is lost or wasted every year.\n"+"Being mindful of portion sizes, proper storage, and understanding food labels can contribute to reducing individual food waste.");
    }//GEN-LAST:event_factBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton checkBtn;
    private javax.swing.JButton factBtn;
    private javax.swing.JCheckBox food1Box;
    private javax.swing.JCheckBox food2Box;
    private javax.swing.JCheckBox food3Box;
    private javax.swing.JCheckBox food4Box;
    private javax.swing.JCheckBox food5Box;
    private javax.swing.JCheckBox food6Box;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JButton scoreBtn;
    private javax.swing.JLabel tagLineLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
