package climateheroapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor Colley
 */
public class QuestionManagementGUI extends javax.swing.JFrame {

    private String question, correction, answ, option1, option2, option3, option4;
    private int id, level;
    private ArrayList<MultipleChoice> mList;
    private ArrayList<TrueOrFalse> tList;

    /**
     * Creates new form QuestionManagementGUI
     */
    public QuestionManagementGUI() {
        initComponents();
        
        //this part of the code loads teh questions to the array list so that we can manipulate them:
        mList = new ArrayList<>();
        tList = new ArrayList<>();

        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            inFile = new File("outputM.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            mList = (ArrayList<MultipleChoice>) oStream.readObject();

            for (MultipleChoice m : mList) {
                m.getQuestion();
                m.getAnsw();
                m.getCorrection();
                m.getId();
                m.getLevel();
                m.getOption1();
                m.getOption2();
                m.getOption3();
                m.getOption4();
            }

            oStream.close();
        } catch (IOException e) {
            System.out.println(e);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
        
        try {
            inFile = new File("outputT.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            tList = (ArrayList<TrueOrFalse>) oStream.readObject();

            for (TrueOrFalse t : tList) {
                t.getQuestion();
                t.getAnsw();
                t.getCorrection();
                t.getId();
                t.getLevel();
                t.getOption1();
                t.getOption2();
            }
            oStream.close();
        } catch (IOException e) {
            System.out.println(e);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }

        optionShowLbl.setVisible(false);
        optionAddLbl.setVisible(false);
        optionDeleteLbl.setVisible(false);

        mCRb.setVisible(false);
        tFRb.setVisible(false);
        deleteLbl.setVisible(false);
        deleteTf.setVisible(false);

        questionLbl.setVisible(false);
        questionTf.setVisible(false);

        correctionLbl.setVisible(false);
        correctionTf.setVisible(false);

        answerLbl.setVisible(false);
        answerTf.setVisible(false);

        levelLbl.setVisible(false);
        levelTf.setVisible(false);

        option1Lbl.setVisible(false);
        option1Tf.setVisible(false);
        option2Lbl.setVisible(false);
        option2Tf.setVisible(false);
        option3Lbl.setVisible(false);
        option3Tf.setVisible(false);
        option4Lbl.setVisible(false);
        option4Tf.setVisible(false);

        saveQBtn.setVisible(false);
        addQBtn.setVisible(false);
        showQBtn.setVisible(false);
        delQBtn.setVisible(false);

        mList = new ArrayList<>();
        tList = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionTypeButtonGroup = new javax.swing.ButtonGroup();
        mCRb = new javax.swing.JRadioButton();
        tFRb = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        showBtn = new javax.swing.JButton();
        questionTf = new javax.swing.JTextField();
        correctionTf = new javax.swing.JTextField();
        questionManagementLbl = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        questionLbl = new javax.swing.JLabel();
        answerLbl = new javax.swing.JLabel();
        correctionLbl = new javax.swing.JLabel();
        answerTf = new javax.swing.JTextField();
        levelTf = new javax.swing.JTextField();
        option1Tf = new javax.swing.JTextField();
        option2Tf = new javax.swing.JTextField();
        option3Tf = new javax.swing.JTextField();
        option4Tf = new javax.swing.JTextField();
        levelLbl = new javax.swing.JLabel();
        option1Lbl = new javax.swing.JLabel();
        option2Lbl = new javax.swing.JLabel();
        option3Lbl = new javax.swing.JLabel();
        option4Lbl = new javax.swing.JLabel();
        saveQBtn = new javax.swing.JButton();
        questionManagementTitleLbl = new javax.swing.JLabel();
        optionAddLbl = new javax.swing.JLabel();
        optionShowLbl = new javax.swing.JLabel();
        optionDeleteLbl = new javax.swing.JLabel();
        addQBtn = new javax.swing.JButton();
        showQBtn = new javax.swing.JButton();
        delQBtn = new javax.swing.JButton();
        deleteTf = new javax.swing.JTextField();
        deleteLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionTypeButtonGroup.add(mCRb);
        mCRb.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        mCRb.setText("Multiple Choice");
        mCRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCRbActionPerformed(evt);
            }
        });

        questionTypeButtonGroup.add(tFRb);
        tFRb.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tFRb.setText("True or False");
        tFRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFRbActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        showBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        questionManagementLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        questionManagementLbl.setText("What do you want to do?");

        deleteBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 204, 255));
        backBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        questionLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        questionLbl.setText("Question:");

        answerLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        answerLbl.setText("Answer:");

        correctionLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        correctionLbl.setText("Correction:");

        option1Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1TfActionPerformed(evt);
            }
        });

        option2Tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2TfActionPerformed(evt);
            }
        });

        levelLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        levelLbl.setText("Level:");

        option1Lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        option1Lbl.setText("Option 1:");

        option2Lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        option2Lbl.setText("Option 2:");

        option3Lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        option3Lbl.setText("Option 3:");

        option4Lbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        option4Lbl.setText("Option 4:");

        saveQBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        saveQBtn.setText("Save Questions");
        saveQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveQBtnActionPerformed(evt);
            }
        });

        questionManagementTitleLbl.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        questionManagementTitleLbl.setText("Question Management");

        optionAddLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        optionAddLbl.setText("What Kind of question do you want to Add?");

        optionShowLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        optionShowLbl.setText("What Kind of question do you want to Show?");

        optionDeleteLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        optionDeleteLbl.setText("What Kind of question do you want to Delete?");

        addQBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        addQBtn.setText("Add Question");
        addQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQBtnActionPerformed(evt);
            }
        });

        showQBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        showQBtn.setText("Show Questions");
        showQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showQBtnActionPerformed(evt);
            }
        });

        delQBtn.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        delQBtn.setText("Delete Question");
        delQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delQBtnActionPerformed(evt);
            }
        });

        deleteTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTfActionPerformed(evt);
            }
        });

        deleteLbl.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        deleteLbl.setText("Enter the ID to delete:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionManagementTitleLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showBtn)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn)
                                .addGap(18, 18, 18)
                                .addComponent(backBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optionAddLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(optionShowLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(optionDeleteLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(correctionLbl)
                                                        .addComponent(levelLbl)
                                                        .addComponent(answerLbl))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(answerTf)
                                                        .addComponent(levelTf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(questionLbl)
                                                    .addGap(105, 138, Short.MAX_VALUE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(questionTf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(correctionTf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mCRb)
                                        .addGap(38, 38, 38)
                                        .addComponent(tFRb)))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option2Lbl)
                                    .addComponent(option3Lbl)
                                    .addComponent(option4Lbl)
                                    .addComponent(option1Lbl)
                                    .addComponent(deleteLbl))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(option1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(option2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(option3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(option4Tf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(deleteTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(questionManagementLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(addQBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveQBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showQBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delQBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(questionManagementTitleLbl)
                .addGap(14, 14, 14)
                .addComponent(questionManagementLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(showBtn)
                    .addComponent(deleteBtn)
                    .addComponent(backBtn))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionAddLbl)
                    .addComponent(optionShowLbl)
                    .addComponent(optionDeleteLbl))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCRb)
                    .addComponent(tFRb)
                    .addComponent(deleteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteLbl))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(questionLbl)
                            .addComponent(questionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correctionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correctionLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answerTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerLbl))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelLbl)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(option2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(option1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(option1Lbl))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(option2Lbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(option3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(option3Lbl))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(option4Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(option4Lbl)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveQBtn)
                    .addComponent(addQBtn)
                    .addComponent(showQBtn)
                    .addComponent(delQBtn))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        // TODO add your handling code here:
        optionShowLbl.setVisible(true);
        optionAddLbl.setVisible(false);
        optionDeleteLbl.setVisible(false);

        mCRb.setVisible(true);
        tFRb.setVisible(true);

        questionLbl.setVisible(false);
        questionTf.setVisible(false);

        correctionLbl.setVisible(false);
        correctionTf.setVisible(false);

        answerLbl.setVisible(false);
        answerTf.setVisible(false);

        levelLbl.setVisible(false);
        levelTf.setVisible(false);

        option1Lbl.setVisible(false);
        option1Tf.setVisible(false);
        option2Lbl.setVisible(false);
        option2Tf.setVisible(false);
        option3Lbl.setVisible(false);
        option3Tf.setVisible(false);
        option4Lbl.setVisible(false);
        option4Tf.setVisible(false);

        saveQBtn.setVisible(false);
        addQBtn.setVisible(false);
        showQBtn.setVisible(false);
        
        deleteLbl.setVisible(false);
        deleteTf.setVisible(false);
        delQBtn.setVisible(false);
        
    }//GEN-LAST:event_showBtnActionPerformed

    private void option2TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2TfActionPerformed

    private void option1TfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1TfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option1TfActionPerformed

    private void mCRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCRbActionPerformed
        // Some elements only show up once an option is selected to prevent a wrong action to occur
        mCRb.setVisible(true);
        tFRb.setVisible(true);

        saveQBtn.setVisible(true);

        if (optionAddLbl.isVisible() == true) {
            
            deleteLbl.setVisible(false);
            deleteTf.setVisible(false);
            
            questionLbl.setVisible(true);
            questionTf.setVisible(true);

            correctionLbl.setVisible(true);
            correctionTf.setVisible(true);

            answerLbl.setVisible(true);
            answerTf.setVisible(true);

            levelLbl.setVisible(true);
            levelTf.setVisible(true);

            option1Lbl.setVisible(true);
            option1Tf.setVisible(true);
            option2Lbl.setVisible(true);
            option2Tf.setVisible(true);
            option3Lbl.setVisible(true);
            option3Tf.setVisible(true);
            option4Lbl.setVisible(true);
            option4Tf.setVisible(true);

            saveQBtn.setVisible(true);
            addQBtn.setVisible(true);
            showQBtn.setVisible(false);

        } else if (optionShowLbl.isVisible() == true) {
            
            deleteLbl.setVisible(false);
            deleteTf.setVisible(false);
            
            questionLbl.setVisible(false);
            questionTf.setVisible(false);

            correctionLbl.setVisible(false);
            correctionTf.setVisible(false);

            answerLbl.setVisible(false);
            answerTf.setVisible(false);

            levelLbl.setVisible(false);
            levelTf.setVisible(false);

            option1Lbl.setVisible(false);
            option1Tf.setVisible(false);
            option2Lbl.setVisible(false);
            option2Tf.setVisible(false);
            option3Lbl.setVisible(false);
            option3Tf.setVisible(false);
            option4Lbl.setVisible(false);
            option4Tf.setVisible(false);

            saveQBtn.setVisible(false);
            addQBtn.setVisible(false);
            showQBtn.setVisible(true);
        } else if (optionDeleteLbl.isVisible() == true) {
            deleteLbl.setVisible(true);
            deleteTf.setVisible(true);
            delQBtn.setVisible(true);
        }
    }//GEN-LAST:event_mCRbActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        optionShowLbl.setVisible(false);
        optionAddLbl.setVisible(true);
        optionDeleteLbl.setVisible(false);

        mCRb.setVisible(true);
        tFRb.setVisible(true);

        questionLbl.setVisible(false);
        questionTf.setVisible(false);

        correctionLbl.setVisible(false);
        correctionTf.setVisible(false);

        answerLbl.setVisible(false);
        answerTf.setVisible(false);

        levelLbl.setVisible(false);
        levelTf.setVisible(false);

        option1Lbl.setVisible(false);
        option1Tf.setVisible(false);
        option2Lbl.setVisible(false);
        option2Tf.setVisible(false);
        option3Lbl.setVisible(false);
        option3Tf.setVisible(false);
        option4Lbl.setVisible(false);
        option4Tf.setVisible(false);

        saveQBtn.setVisible(false);
        addQBtn.setVisible(false);
        showQBtn.setVisible(false);
        
        deleteLbl.setVisible(false);
        deleteTf.setVisible(false);
        delQBtn.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        optionShowLbl.setVisible(false);
        optionAddLbl.setVisible(false);
        optionDeleteLbl.setVisible(true);

        mCRb.setVisible(true);
        tFRb.setVisible(true);

        questionLbl.setVisible(false);
        questionTf.setVisible(false);

        correctionLbl.setVisible(false);
        correctionTf.setVisible(false);

        answerLbl.setVisible(false);
        answerTf.setVisible(false);

        levelLbl.setVisible(false);
        levelTf.setVisible(false);

        option1Lbl.setVisible(false);
        option1Tf.setVisible(false);
        option2Lbl.setVisible(false);
        option2Tf.setVisible(false);
        option3Lbl.setVisible(false);
        option3Tf.setVisible(false);
        option4Lbl.setVisible(false);
        option4Tf.setVisible(false);

        saveQBtn.setVisible(false);
        addQBtn.setVisible(false);
        showQBtn.setVisible(false);


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void tFRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFRbActionPerformed
        // TODO add your handling code here:
        mCRb.setVisible(true);
        tFRb.setVisible(true);

        saveQBtn.setVisible(true);

        if (optionAddLbl.isVisible() == true) {
            questionLbl.setVisible(true);
            questionTf.setVisible(true);

            correctionLbl.setVisible(true);
            correctionTf.setVisible(true);

            answerLbl.setVisible(true);
            answerTf.setVisible(true);

            levelLbl.setVisible(true);
            levelTf.setVisible(true);

            option1Lbl.setVisible(true);
            option1Tf.setVisible(true);
            option2Lbl.setVisible(true);
            option2Tf.setVisible(true);
            option3Lbl.setVisible(false);
            option3Tf.setVisible(false);
            option4Lbl.setVisible(false);
            option4Tf.setVisible(false);

            saveQBtn.setVisible(true);
            addQBtn.setVisible(true);
            showQBtn.setVisible(false);

        } else if (optionShowLbl.isVisible() == true) {
            questionLbl.setVisible(false);
            questionTf.setVisible(false);

            correctionLbl.setVisible(false);
            correctionTf.setVisible(false);

            answerLbl.setVisible(false);
            answerTf.setVisible(false);

            levelLbl.setVisible(false);
            levelTf.setVisible(false);

            option1Lbl.setVisible(false);
            option1Tf.setVisible(false);
            option2Lbl.setVisible(false);
            option2Tf.setVisible(false);
            saveQBtn.setVisible(false);
            addQBtn.setVisible(false);
            showQBtn.setVisible(true);
        } else if (optionDeleteLbl.isVisible() == true) {
            deleteLbl.setVisible(true);
            deleteTf.setVisible(true);
            delQBtn.setVisible(true);
        }
    }//GEN-LAST:event_tFRbActionPerformed

    private void saveQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveQBtnActionPerformed
        // Depending on which button is selected, different actions take place even if the same button is pressed

        if (mCRb.isSelected()) {

            File outFile;
            FileOutputStream fStream;
            ObjectOutputStream oStream;

            try {
                outFile = new File("outputM.data");
                fStream = new FileOutputStream(outFile);
                oStream = new ObjectOutputStream(fStream);

                oStream.writeObject(mList);

                JOptionPane.showMessageDialog(null, "File written successfully!");
            } catch (IOException e) {
                System.out.println(e);
            }

        } else if (tFRb.isSelected()) {

            File outFile;
            FileOutputStream fStream;
            ObjectOutputStream oStream;

            try {
                outFile = new File("outputT.data");
                fStream = new FileOutputStream(outFile);
                oStream = new ObjectOutputStream(fStream);

                oStream.writeObject(tList);

                JOptionPane.showMessageDialog(null, "File written successfully!");
            } catch (IOException e) {
                System.out.println(e);
            }

        }

    }//GEN-LAST:event_saveQBtnActionPerformed

    private void addQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQBtnActionPerformed
        // TODO add your handling code here:
        if (tFRb.isSelected()) {
            question = questionTf.getText();
            correction = correctionTf.getText();
            answ = answerTf.getText();
            level = Integer.parseInt(levelTf.getText());
            option1 = option1Tf.getText();
            option2 = option2Tf.getText();
            
            //This code generates different IDs based on the existing ones, replacing missing numbers so that they can be selected as potential questions
            int count = 1;
            for (TrueOrFalse t : tList) {
                if (count == t.getId()) {
                    count++;
                }
            }
            id = count;

            TrueOrFalse t = new TrueOrFalse();
            t.setQuestion(question);
            t.setCorrection(correction);
            t.setAnsw(answ);
            t.setLevel(level);
            t.setOption1(option1);
            t.setOption2(option2);
            t.setId(id);

            tList.add(t);
            JOptionPane.showMessageDialog(null, "The question with id: " + t.getId() + " has been created.");

        }
        if (mCRb.isSelected()) {
            question = questionTf.getText();
            correction = correctionTf.getText();
            answ = answerTf.getText();
            level = Integer.parseInt(levelTf.getText());
            option1 = option1Tf.getText();
            option2 = option2Tf.getText();
            option3 = option3Tf.getText();
            option4 = option4Tf.getText();

            
          
            int count = 1;
            for (MultipleChoice m : mList) {
                if (count == m.getId()) {
                    count++;
                }
            }
            id = count;

             

            MultipleChoice m = new MultipleChoice();
            m.setQuestion(question);
            m.setCorrection(correction);
            m.setAnsw(answ);
            m.setLevel(level);
            m.setOption1(option1);
            m.setOption2(option2);
            m.setOption3(option3);
            m.setOption4(option4);
            m.setId(id);

            mList.add(m);
            JOptionPane.showMessageDialog(null, "The question with id: " + m.getId() + " has been created.");

        }
    }//GEN-LAST:event_addQBtnActionPerformed

    private void showQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showQBtnActionPerformed
        // This code reads the questions which have been saved to the file
        if (mCRb.isSelected()) {
            File inFile;
            FileInputStream fStream;
            ObjectInputStream oStream;

            try {
                inFile = new File("outputM.data");
                fStream = new FileInputStream(inFile);
                oStream = new ObjectInputStream(fStream);

                mList = (ArrayList<MultipleChoice>) oStream.readObject();

                for (MultipleChoice m : mList) {
                    JOptionPane.showMessageDialog(null, "Question: " + m.getQuestion() + ", Answer: " + m.getAnsw() + ", Correction: " + m.getCorrection() + ", Level: " + m.getLevel() + ", Id: " + m.getId() + ", Option 1: " + m.getOption1() + ", Option 2: " + m.getOption2() + ", Option 3: " + m.getOption3() + ", Option 4: " + m.getOption4() + ".");
                }

                oStream.close();
            } catch (IOException e) {
                System.out.println(e);
            } catch (ClassNotFoundException ex) {
                System.out.println(ex);
            }
        } else if (tFRb.isSelected()) {
            File inFile;
            FileInputStream fStream;
            ObjectInputStream oStream;

            try {
                inFile = new File("outputT.data");
                fStream = new FileInputStream(inFile);
                oStream = new ObjectInputStream(fStream);

                tList = (ArrayList<TrueOrFalse>) oStream.readObject();

                for (TrueOrFalse t : tList) {
                    JOptionPane.showMessageDialog(null, "Question: " + t.getQuestion() + ", Answer: " + t.getAnsw() + ", Correction: " + t.getCorrection() + ", Level: " + t.getLevel() + ", Id: " + t.getId() + ", Option 1: " + t.getOption1() + ", Option 2: " + t.getOption2() + ".");
                }
                oStream.close();
            } catch (IOException e) {
                System.out.println(e);
            } catch (ClassNotFoundException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_showQBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // This button returns to the previous GUI
        ClimateHeroQuizGUI myGUI = new ClimateHeroQuizGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void delQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delQBtnActionPerformed
        // TODO add your handling code here:
        if (tFRb.isSelected()) {
            int i = 0;
            int j = 0;
            for (TrueOrFalse t : tList) {
                i++;
                if (t.getId() == Integer.parseInt(deleteTf.getText())) {
                    tList.remove(t);
                    JOptionPane.showMessageDialog(null, "The question with id: " + t.getId() + " has been deleted.");
                }
                else{
                    j++;
                }
            }
            if(i==j){
                JOptionPane.showMessageDialog(null, "This ID does not exist!");
            }
        } else if (mCRb.isSelected()) {
            int i = 0;
            int j = 0;
            for (MultipleChoice m : mList) {
                i++;
                if (m.getId() == Integer.parseInt(deleteTf.getText())) {
                    mList.remove(m);
                    JOptionPane.showMessageDialog(null, "The question with id: " + m.getId() + " has been deleted.");
                }
                else{
                    j++;
                }
            }
            if(i==j){
                JOptionPane.showMessageDialog(null, "This ID does not exist!");
            }
        }
    }//GEN-LAST:event_delQBtnActionPerformed

    private void deleteTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionManagementGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addQBtn;
    private javax.swing.JLabel answerLbl;
    private javax.swing.JTextField answerTf;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel correctionLbl;
    private javax.swing.JTextField correctionTf;
    private javax.swing.JButton delQBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel deleteLbl;
    private javax.swing.JTextField deleteTf;
    private javax.swing.JLabel levelLbl;
    private javax.swing.JTextField levelTf;
    private javax.swing.JRadioButton mCRb;
    private javax.swing.JLabel option1Lbl;
    private javax.swing.JTextField option1Tf;
    private javax.swing.JLabel option2Lbl;
    private javax.swing.JTextField option2Tf;
    private javax.swing.JLabel option3Lbl;
    private javax.swing.JTextField option3Tf;
    private javax.swing.JLabel option4Lbl;
    private javax.swing.JTextField option4Tf;
    private javax.swing.JLabel optionAddLbl;
    private javax.swing.JLabel optionDeleteLbl;
    private javax.swing.JLabel optionShowLbl;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JLabel questionManagementLbl;
    private javax.swing.JLabel questionManagementTitleLbl;
    private javax.swing.JTextField questionTf;
    private javax.swing.ButtonGroup questionTypeButtonGroup;
    private javax.swing.JButton saveQBtn;
    private javax.swing.JButton showBtn;
    private javax.swing.JButton showQBtn;
    private javax.swing.JRadioButton tFRb;
    // End of variables declaration//GEN-END:variables
}
