/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateheroapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Prathibha Kirthi
 */
public class WasteGUI extends javax.swing.JFrame {
    private ArrayList <Waste> actions;
    int score;
    double carbon;

    /**
     * Creates new form WasteGUI
     */
    public WasteGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        taglineLbl = new javax.swing.JLabel();
        waste1Box = new javax.swing.JCheckBox();
        waste2Box = new javax.swing.JCheckBox();
        waste3Box = new javax.swing.JCheckBox();
        waste4Box = new javax.swing.JCheckBox();
        waste5Box = new javax.swing.JCheckBox();
        waste6Box = new javax.swing.JCheckBox();
        scoreBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        checkBtn = new javax.swing.JButton();
        factBtn = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        questionLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 153, 153));
        titleLbl.setText("\"Waste Less, Live More: Embrace Responsible Choices for a Cleaner, Greener Future!\"");

        taglineLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        taglineLbl.setForeground(new java.awt.Color(255, 0, 51));
        taglineLbl.setText("Please select any of the options that you did today for a cleaner environment !");

        waste1Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        waste1Box.setText("Recycled paper, plastic, glass, and metal.");
        waste1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waste1BoxActionPerformed(evt);
            }
        });

        waste2Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        waste2Box.setText("Opted for products with eco-friendly packaging.");
        waste2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waste2BoxActionPerformed(evt);
            }
        });

        waste3Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        waste3Box.setText("Used reusable shopping bags ");
        waste3Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waste3BoxActionPerformed(evt);
            }
        });

        waste4Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        waste4Box.setText("Participated in clothing swaps or second-hand shopping.");
        waste4Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waste4BoxActionPerformed(evt);
            }
        });

        waste5Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        waste5Box.setText("Upcycled or reused products ");
        waste5Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waste5BoxActionPerformed(evt);
            }
        });

        waste6Box.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        waste6Box.setText("Practice hazardous waste disposal ");
        waste6Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waste6BoxActionPerformed(evt);
            }
        });

        scoreBtn.setBackground(new java.awt.Color(51, 255, 255));
        scoreBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        scoreBtn.setText("Score");
        scoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 204, 255));
        backBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        checkBtn.setBackground(new java.awt.Color(51, 255, 255));
        checkBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        checkBtn.setText("Check me! ");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        factBtn.setBackground(new java.awt.Color(51, 255, 255));
        factBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        factBtn.setText("Fact of the day");
        factBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factBtnActionPerformed(evt);
            }
        });

        questionLbl.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        questionLbl.setText("How happy were you with your contribution today ?");
        questionLbl.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)), null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(scoreBtn)
                        .addGap(46, 46, 46)
                        .addComponent(checkBtn)
                        .addGap(41, 41, 41)
                        .addComponent(factBtn)
                        .addGap(78, 78, 78)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waste6Box, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(waste4Box, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLbl)
                    .addComponent(taglineLbl)
                    .addComponent(waste1Box, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waste2Box, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waste3Box, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waste5Box, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(questionLbl)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addComponent(taglineLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waste1Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(waste2Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(waste3Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(waste4Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waste5Box, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(questionLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waste6Box, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreBtn)
                    .addComponent(backBtn)
                    .addComponent(checkBtn)
                    .addComponent(factBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBtnActionPerformed
        // TODO add your handling code here:
        
            JOptionPane.showMessageDialog(null,"Your Score is:"+score);
        
        
    }//GEN-LAST:event_scoreBtnActionPerformed

    private void waste1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waste1BoxActionPerformed
        // TODO add your handling code here:
        if (waste1Box.isSelected()) {
                    score  = score + 5;
                    carbon = carbon + 14.12;
                }
    }//GEN-LAST:event_waste1BoxActionPerformed

    private void waste2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waste2BoxActionPerformed
        // TODO add your handling code here:
        if (waste2Box.isSelected()) {
                    score  = score + 5;
                    carbon = carbon + 14.57;
                }
    }//GEN-LAST:event_waste2BoxActionPerformed

    private void waste3BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waste3BoxActionPerformed
        // TODO add your handling code here:
        if (waste3Box.isSelected()) {
                    score  = score + 5;
                    carbon =  carbon +17.12;
                }
    }//GEN-LAST:event_waste3BoxActionPerformed

    private void waste4BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waste4BoxActionPerformed
        // TODO add your handling code here:
        if (waste4Box.isSelected()) {
                    score  = score + 5;
                    carbon=  carbon +19.13;
                }
    }//GEN-LAST:event_waste4BoxActionPerformed

    private void waste5BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waste5BoxActionPerformed
        // TODO add your handling code here:
        if (waste5Box.isSelected()) {
                    score  = score + 5;
                    carbon = carbon + 16.90;
                }
    }//GEN-LAST:event_waste5BoxActionPerformed

    private void waste6BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waste6BoxActionPerformed
        // TODO add your handling code here:
        if (waste6Box.isSelected()) {
                    score  = score + 5;
                    carbon =  carbon + 22.12;
                }
    }//GEN-LAST:event_waste6BoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ClimateHeroCarbonGUI myGUI = new ClimateHeroCarbonGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Carbon footprint that you have NOT emitted because of doing your activities is:"+carbon+" CO2e");
    }//GEN-LAST:event_checkBtnActionPerformed

    private void factBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Waste management follows a hierarchy that prioritizes prevention, reduction, reuse, recycling, energy recovery, and, finally, disposal.\n" +
"Implementing the waste management hierarchy helps minimize the environmental impact of waste and promotes a circular economy.");
    }//GEN-LAST:event_factBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WasteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WasteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WasteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WasteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WasteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton checkBtn;
    private javax.swing.JButton factBtn;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JButton scoreBtn;
    private javax.swing.JLabel taglineLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JCheckBox waste1Box;
    private javax.swing.JCheckBox waste2Box;
    private javax.swing.JCheckBox waste3Box;
    private javax.swing.JCheckBox waste4Box;
    private javax.swing.JCheckBox waste5Box;
    private javax.swing.JCheckBox waste6Box;
    // End of variables declaration//GEN-END:variables
}
